theme: minima
title: Gelhaus Lab
description: Welcome to our research lab website!
url  : https://GelahusLab.github.io
# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  pronouns         :  "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Pittsburgh"
  employer         : "University of Pittsburgh"
  email            : "none@example.org" 
# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
